### ISSUE TITLE
findDOMNode was called on an unmounted component

### ISSUE THREAD

**Issue by lorensr** [azmenak/react-stripe-checkout#134]
I'm getting this error after I click "Pay $10", when my page then rerenders without `<StripeCheckout>`. I'm not calling `findDOMNode`, but I'm guessing Checkout is?

```
inner-284ced8932f4a8…085eeb162a4124.js:6 Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (https://checkout.stripe.com/m/lib/inner-284ced8932f4a845e0085eeb162a4124.js:6:27558)
    at Object.r [as findDOMNode] (https://checkout.stripe.com/m/lib/inner-284ced8932f4a845e0085eeb162a4124.js:62:194)
    at t (https://checkout.stripe.com/m/lib/inner-284ced8932f4a845e0085eeb162a4124.js:37:22320)
    at r (https://checkout.stripe.com/m/lib/inner-284ced8932f4a845e0085eeb162a4124.js:58:14240)
```

**Comment by samcpop** [comment]
I'm getting the same error. I don't suppose you found a solution, did you?

**Comment by phongle2512** [comment]
I got the same error ? Btw, how can we enable apple pay, google pay like alipay ?

**Comment by LanguageXange** [comment]
Did you find a solution?

**Comment by anjanesh** [comment]
I'm getting the same error - React 16.8
