### ISSUE TITLE
Typescript error:  JSX element type 'StripeCheckout' does not have any construct or call signatures

### ISSUE THREAD

**Issue by JulsRicketti** [azmenak/react-stripe-checkout#87]
It sounds very similar to issue #80, however the solution proposed in that thread doesn't seem to solve this problem.

It is happening in the simple use case for the StripeCheckout component:

```
import * as StripeCheckout from 'react-stripe-checkout'
.
.
.
render () {
   return (
      <div>
        <h1>Payment page</h1>
        <StripeCheckout
        token={this.onToken}
        stripeKey="pk_test_SOMETHING"
      </div>
    )
}
```

The full error message is:
> error TS2604: JSX element type 'StripeCheckout' does not have any construct or call signatures

Not sure if relevant, but in case it is, here is the full log:

```
at getOutput (ProjectPath/node_modules/ts-node/src/index.ts:302:15)
    at ProjectPath/node_modules/ts-node/src/index.ts:333:16
    at Object.compile (ProjectPath/node_modules/ts-node/src/index.ts:492:17)
    at Module.m._compile (ProjectPath/node_modules/ts-node/src/index.ts:385:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (ProjectPath/node_modules/ts-node/src/index.ts:388:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (ProjectPath/web/src/routing/lib/site.js:32:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (ProjectPath/node_modules/ts-node/src/index.ts:385:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (ProjectPath/node_modules/ts-node/src/index.ts:388:12)
```

**Comment by JulsRicketti** [comment]
Quick follow up: It was solved by changing my import statement to simply `import StripeCheckout from 'react-stripe-checkout'`
